# Load environment variables from .env (optional)
spring.config.import=optional:dotenv:

spring.application.name=personal-trainer

# Server configuration
server.port=8080

# Default datasource (in-memory for local development)
#spring.datasource.url=jdbc:postgresql://localhost:5433/personal-trainer
spring.datasource.url=jdbc:postgresql://ep-falling-pond-amdgh2ft-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

