spring.application.name=personal-trainer

# Server configuration
server.port=8080

# Default datasource (in-memory H2 for local development)
# spring.datasource.url=jdbc:h2:mem:personal-trainer;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
# spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:postgresql://localhost:5433/personal-trainer
spring.datasource.username=postgres
spring.datasource.password=criscut28

spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# spring.jpa.properties.hibernate.format_sql=true
# logging.level.org.hibernate.type.descriptor.sql=TRACE